# Generated by Django 4.2.7 on 2024-04-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_updated',
            field=models.DateTimeField(),
        ),
    ]
