# Generated by Django 4.2.7 on 2024-04-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_note_note_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
