# Generated by Django 4.2.7 on 2024-03-24 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teammember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm_name', models.CharField(max_length=64)),
                ('tm_lname', models.CharField(max_length=128)),
                ('tm_seniority', models.CharField(choices=[('intern', 'Internship'), ('junior', 'Junior level'), ('regular', 'Mid-level'), ('senior', 'Senior level'), ('expert', 'Expert level')], max_length=64)),
                ('tm_position', models.CharField(choices=[('sm', 'Scrum Master'), ('fe_dev', 'Frontend Developer'), ('be_dev', 'Backend Developer'), ('devops', 'DevOps'), ('des', 'Designer'), ('qa', 'Quality Engineer'), ('ba', 'Business Analyst'), ('sa', 'Solution Architect')], max_length=64)),
                ('tm_joined', models.DateField()),
                ('tm_summary', models.TextField(blank=True, max_length=250)),
                ('tm_photo', models.ImageField(upload_to='profile_pictures/')),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
