# Generated by Django 4.2.7 on 2024-03-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='tm_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='tm_seniority',
            field=models.CharField(blank=True, choices=[('intern', 'Internship'), ('junior', 'Junior level'), ('regular', 'Mid-level'), ('senior', 'Senior level'), ('expert', 'Expert level')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='tm_summary',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
