# Generated by Django 4.2.7 on 2024-03-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_teammember_tm_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='tm_seniority',
            field=models.CharField(blank=True, choices=[('intern', 'Internship'), ('junior', 'Junior level'), ('regular', 'Medium level'), ('senior', 'Senior level'), ('expert', 'Expert level')], max_length=64, null=True),
        ),
    ]
