# Generated by Django 4.2.7 on 2024-04-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_teammember_tm_seniority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='tm_photo',
            field=models.ImageField(blank=True, null=True, upload_to='teammembers_profile_pictures/'),
        ),
    ]
