# Generated by Django 4.2.7 on 2024-03-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('sm', 'Scrum Master'), ('pm', 'Project Manager'), ('po', 'Product Owner'), ('dev', 'Developer'), ('tl', 'Team leader'), ('des', 'Designer'), ('qa', 'Quality Engineer'), ('ba', 'Businesss Analyst'), ('head', 'Head of Department'), ('ceo', 'Chief executive officer')], max_length=64, null=True),
        ),
    ]
