# Generated by Django 4.2.7 on 2024-04-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_profile_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birthday',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('sm', 'Scrum Master'), ('pm', 'Project Manager'), ('po', 'Product Owner'), ('dev', 'Developer'), ('tl', 'Team leader'), ('des', 'Designer'), ('qa', 'Quality Engineer'), ('ba', 'Businesss Analyst'), ('head', 'Head of Department'), ('ceo', 'Chief executive officer')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription',
            field=models.CharField(choices=[('basic', 'Basic')], default='basic', max_length=32),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
